version: 0.2

phases:
    pre_build:
        commands:
        - echo Copying hadolint.yml to the application directory
        - cp $CODEBUILD_SRC_DIR/hadolint.yml $CODEBUILD_SRC_DIR_APPSOURCE/hadolint.yml
        - echo Switching to the application directory
        - cd $CODEBUILD_SRC_DIR_APPSOURCE
        - echo Pulling the hadolint docker image
        - docker pull hadolint/hadolint:v1.17.5
    build:
        commands:
        - echo Build started on `date`
        - echo Scanning with Hadolint...          
        - result=`docker run --rm -i -v ${PWD}/hadolint.yml:/.hadolint.yaml hadolint/hadolint:v1.17.5 hadolint -f json - < Dockerfile`
    post_build:
        commands:
        - echo $result
        - App_Name=`aws ssm get-parameter --name "devsecops_App_Name" | jq .Parameter.Value | sed 's/\"//g'`
        - dockerfile_result_key="${App_Name}_dockerfile_result"
        - aws ssm put-parameter --name $dockerfile_result_key --type "String" --value "$result" --overwrite
        - echo Build completed on `date`
