version: 0.2

phases:
  pre_build:
    commands:
    - echo Copying secrets_config.json to the application directory
    - cp $CODEBUILD_SRC_DIR/secrets_config.json $CODEBUILD_SRC_DIR_APPSOURCE/secrets_config.json
    - echo Switching to the application directory
    - cd $CODEBUILD_SRC_DIR_APPSOURCE
    - echo Installing truffleHog
    - which pip3 && pip3 --version
    - which python3 && python3 --version
    - pip3 install 'truffleHog>=2.1.0,<3.0'
  build:
    commands:
    - echo Build started on `date`
    - echo Scanning with truffleHog...
    - trufflehog --regex --rules secrets_config.json --entropy=False --max_depth 1 file:///$PWD/
  post_build:
    commands:
    - echo Build completed on `date`
