version: 0.2

phases:
  pre_build:
    commands:
      - echo Start build application.
      - sonar_host_url=`aws ssm get-parameter --name "decsecops_Sonar_URL" | jq .Parameter.Value | sed 's/\"//g'`
      - sonar_project_key=`aws ssm get-parameter --name "devsecops_App_Name" | jq .Parameter.Value | sed 's/\"//g'`
      - sonar_username=$(aws secretsmanager get-secret-value --secret-id SonarQubeUserSecret | jq -r '.SecretString' | jq -r '.username')
      - sonar_password=$(aws secretsmanager get-secret-value --secret-id SonarQubeUserSecret | jq -r '.SecretString' | jq -r '.password')
      - echo Switching to the application directory
      - cd $CODEBUILD_SRC_DIR_APPSOURCE

  build:
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
      - mvn install
      - mvn clean sonar:sonar -Dsonar.projectKey=$sonar_project_key -Dsonar.host.url=$sonar_host_url -Dsonar.login=$sonar_username -Dsonar.password=$sonar_password -Dsonar.branch.name=develop
      - echo $result

  post_build:
    commands:
      - sonar_link=$(echo $result | egrep -o "you can browse http://[^, ]+")
      - echo $sonar_link
      - sonar_task_id=$(echo $result | egrep -o "task\?id=[^ ]+" | cut -d'=' -f2)
      - | # Allow time for SonarQube Background Task to complete
        stat="PENDING";
        while [ "$stat" != "SUCCESS" ]; do
          if [ $stat = "FAILED" ] || [ $stat = "CANCELLED" ]; then
            echo "SonarQube task $sonar_task_id failed";
            exit 1;
          fi
          stat=$(curl -u "$sonar_username:$sonar_password" $sonar_host_url/api/ce/task\?id=$sonar_task_id | jq -r '.task.status');
          echo "SonarQube analysis status is $stat";
          sleep 5;
        done
      - sonar_analysis_id=$(curl -u "$sonar_username:$sonar_password" $sonar_host_url/api/ce/task\?id=$sonar_task_id | jq -r '.task.analysisId')
      - quality_status=$(curl -u "$sonar_username:$sonar_password" $sonar_host_url/api/qualitygates/project_status\?analysisId=$sonar_analysis_id | jq -r '.projectStatus.status')
      - echo $quality_status
      - |
        if [ $quality_status != "OK" ]; then
          echo "SonarQube analysis Failed or Quality Gate Failed.\n\nFor details, $sonar_link");
          exit "Quality Gate Status: $quality_status"
        fi 
